# Generated by Django 4.2.3 on 2023-07-30 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('img_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedimage',
            name='text',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
