# Generated by Django 4.2.3 on 2023-07-31 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('img_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedimage',
            name='json_response',
            field=models.JSONField(blank=True, null=True, verbose_name='api_json'),
        ),
    ]
