# Generated by Django 4.2.3 on 2023-08-01 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('img_api', '0002_generatedimage_json_response'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generatedimage',
            name='json_response',
        ),
        migrations.AddField(
            model_name='generatedimage',
            name='img_bytes',
            field=models.BinaryField(blank=True, null=True, verbose_name='Img Binary'),
        ),
    ]
